# Generated by Django 5.2.14 on 2026-07-03 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('details', models.TextField(blank=True, default=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='apikey',
            name='length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
